let colorPalette = {
    "Actually": '#800000',
    "Adjective": '#9A6324',
    "Adverb": '#808000',
    "Ambiguous Compound Nouns": '#469990',
    "Ambiguous Nominalization": '#000075',
    "Ambiguous Plural": '#e6194B',
    "Ambiguous Positioning": '#f58231',
    "Ambiguous Words": '#ffe119',
    "Both": '#bfef45',
    "Comparative Verbs": '#3cb44b',
    "Continuance": '#42d4f4',
    "Dangerous Plural": '#4363d8',
    "Dangerous Reference Plural": '#911eb4',
    "Imprecise": '#f032e6',
    "Inside Behaviour": '#a9a9a9',
    "Missing Content": '#fabebe',
    "Negative": '#ffd8b1',
    "Negative Reason": '#fffac8',
    "Optional": '#aaffc3',
    "Passive Ambiguity": '#e6beff',
    "Postfix coordination of two nouns": '#F48FB1',
    "Pronoun": '#F48FB1',
    "Unclear Inclusion": '#196F3D',
    "Vague": '#884EA0',
    "Weak": '#DC7633',
    "Wishful Thinking": '#E74C3C',
    "Default": '#ffff00'
};

let colourPallete = {
    "Actually": '#023fa5',
    "Adjective": '#7d87b9',
    "Adverb": '#bec1d4',
    "Ambiguous Compound Nouns": '#d6bcc0',
    "Ambiguous Nominalization": '#bb7784',
    "Ambiguous Plural": '#8e063b',
    "Ambiguous Positioning": '#4a6fe3',
    "Ambiguous Words": '#8595e1',
    "Both": '#b5bbe3',
    "Comparative Verbs": '#e6afb9',
    "Continuance": '#e07b91',
    "Dangerous Plural": '#d33f6a',
    "Dangerous Reference Plural": '#11c638',
    "Imprecise": '#8dd593',
    "Inside Behaviour": '#c6dec7',
    "Missing Content": '#ead3c6',
    "Negative": '#f0b98d',
    "Negative Reason": '#ef9708',
    "Optional": '#0fcfc0',
    "Passive Ambiguity": '#9cded6',
    "Pronoun": '#d5eae7',
    "Speculation": '#f3e1eb',
    "Too Broad": '#f6c4e1',
    "Unclear Associativity": '#f79cd4'
}